#!/bin/bash
##################################
# gternet-cli Interface
# By: Knots 12-6-17
# Alpha v0.2
#
##################################

function deploy_service {
    if [ "$SRV" == "netbridge" ]; then
	printf "${grn}DEPLOYING OPENVPN P2P INTERMESH NODE!${end}"
        echo " "
        export P2PUSR="$ARG3"
        export PASS="$ARG4"
        export NODE_ID="$ARG5"
        scripts/netbridge_functions.sh

    elif [ "$SRV" == "mesh" ]; then
        printf "${grn}DEPLOYING A NEW MESHED DEVICE${end}"
        echo " "
        export IFACE="$ARG3"
        scripts/mesh_functions.sh

    elif [ "$SRV" == "server" ]; then
        printf "${grn}Deploying optimized server configuration${end} ${red}(FRESH INSTALLS ONLY! ONLY TESTED ON DEBIAN/RASPBIAN)${end}"
        echo " "
        source scripts/server_functions.sh
        machine_info
        set_motd
        set_sudoers
        set_sshd
        set_sources
        set_sysctl
        install_misc
        set_misc
    fi
}


# CHECK FOR ROOT
if [ "$USER" != "root" ];then
    echo "Please, run the script as root from /root/git/gternet-cli!"
    exit 1
fi

# IMPORT FUNCTIONS FROM SCRIPTS DIR
source scripts/*.sh

# DEFINE SOME COLORS FOR OUTPUT
red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
end=$'\e[0m'
#echo "error check 2"

# DEFINE ARGS FOR DETERMINING WHAT TO DO INPUT
OP=$1
SRV=$2
#echo "error check 3"

if [ "$OP" == "deploy" ]; then
    ARG3=$3
    ARG4=$4
    ARG5=$5
    deploy_service

elif [ "$OP" == "services" ]; then
    printf "${red}Sorry! This feature is still in DEV${end}"
    echo " "

elif [ "$OP" == "help" ]; then
    show_help
    #else
    #printf "${red}Sorry! that is an invalid command${end}"
    #echo " "
    #show_help
fi
